package:
  name: epics-synapps
  version: R5_8

source:
  fn: synApps_5_8.tar.gz
  url: http://www.aps.anl.gov/bcda/synApps/tar/synApps_5_8.tar.gz
  md5: aadd9488337cc4ad8dc8254dbd9fa896

build:
  number: 1
  detect_binary_files_with_prefix: 1

requirements:
  build:
    - epics-base >=3.14.12.5
    - readline
    - hdf5
    - szip
    # might need this too... or we could just install it on the build machine
    # and forget about it!
    #- re2c

  run:
    - epics-base >=3.14.12.5
    - readline

about:
    home: http://www.aps.anl.gov/bcda/synApps
    license: Epics Open License
    summary: synApps is a collection of software tools that help to create a control system for beamlines.
